from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_jwt_extended import JWTManager
from flask_cors import CORS
from flask_mail import Mail
from flask_socketio import SocketIO
from dotenv import load_dotenv
import os

load_dotenv()

db = SQLAlchemy()
migrate = Migrate()
jwt = JWTManager()
mail = Mail()
socketio = SocketIO()


def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = os.getenv("SECRET_KEY", "dev-secret")
    app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv("DATABASE_URL", "sqlite:///nr_sabji_mandi.db")
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    app.config["JWT_SECRET_KEY"] = os.getenv("JWT_SECRET_KEY", "jwt-secret")
    app.config["JWT_ACCESS_TOKEN_EXPIRES"] = 86400

    app.config["MAIL_SERVER"] = os.getenv("MAIL_SERVER", "smtp.gmail.com")
    app.config["MAIL_PORT"] = int(os.getenv("MAIL_PORT", 587))
    app.config["MAIL_USE_TLS"] = os.getenv("MAIL_USE_TLS", "True") == "True"
    app.config["MAIL_USERNAME"] = os.getenv("MAIL_USERNAME")
    app.config["MAIL_PASSWORD"] = os.getenv("MAIL_PASSWORD")
    app.config["MAIL_DEFAULT_SENDER"] = os.getenv("MAIL_DEFAULT_SENDER")

    db.init_app(app)
    migrate.init_app(app, db)
    jwt.init_app(app)
    mail.init_app(app)
    CORS(app, resources={r"/api/*": {"origins": "*"}})
    socketio.init_app(app, cors_allowed_origins="*", async_mode="threading")

    from app.routes.auth import auth_bp
    from app.routes.products import products_bp
    from app.routes.orders import orders_bp
    from app.routes.admin import admin_bp
    from app.routes.analytics import analytics_bp
    from app.routes.chatbot import chatbot_bp
    from app.routes.search import search_bp
    from app.routes.customers import customers_bp

    app.register_blueprint(auth_bp,       url_prefix="/api/auth")
    app.register_blueprint(products_bp,   url_prefix="/api/products")
    app.register_blueprint(orders_bp,     url_prefix="/api/orders")
    app.register_blueprint(admin_bp,      url_prefix="/api/admin")
    app.register_blueprint(analytics_bp,  url_prefix="/api/analytics")
    app.register_blueprint(chatbot_bp,    url_prefix="/api/chatbot")
    app.register_blueprint(search_bp,     url_prefix="/api/search")
    app.register_blueprint(customers_bp,  url_prefix="/api/customers")

    with app.app_context():
        db.create_all()
        _seed_default_admin()
        _seed_sample_products()

    return app


def _seed_default_admin():
    from app.models.user import User
    if not User.query.filter_by(role="admin").first():
        admin = User(name="NR Admin", email="admin@nrsabjimandi.com", phone="9999999999", role="admin")
        admin.set_password("Admin@123")
        db.session.add(admin)
        db.session.commit()
        print("Default admin created: admin@nrsabjimandi.com / Admin@123")


def _seed_exotic_only():
    """Add exotic products if not already present."""
    from app.models.product import Product
    exotic = [
        dict(name="Asparagus", name_hi="शतावरी", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=129, unit="200g", stock_quantity=20, is_available=True, is_featured=True,
             description="Fresh green asparagus spears",
             image_url="https://images.unsplash.com/photo-1539375665275-f9de415ef9ac?w=400&q=80"),
        dict(name="Cherry Tomatoes", name_hi="चेरी टमाटर", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=89, unit="250g", stock_quantity=30, is_available=True,
             description="Sweet cherry tomatoes",
             image_url="https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400&q=80"),
        dict(name="Red Bell Pepper", name_hi="लाल शिमला मिर्च", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=79, unit="piece", stock_quantity=40, is_available=True,
             description="Sweet red capsicum",
             image_url="https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80"),
        dict(name="Yellow Bell Pepper", name_hi="पीली शिमला मिर्च", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=79, unit="piece", stock_quantity=40, is_available=True,
             description="Sweet yellow capsicum",
             image_url="https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80"),
        dict(name="Zucchini (Green)", name_hi="हरी तोरी", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=69, unit="piece", stock_quantity=25, is_available=True,
             description="Fresh green zucchini",
             image_url="https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?w=400&q=80"),
        dict(name="Portobello Mushroom", name_hi="पोर्टोबेलो मशरूम", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=149, unit="200g", stock_quantity=15, is_available=True,
             description="Large meaty portobello mushrooms",
             image_url="https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=400&q=80"),
        dict(name="Celery", name_hi="अजमोद", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=59, unit="200g", stock_quantity=20, is_available=True,
             description="Fresh crispy celery stalks",
             image_url="https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=400&q=80"),
        dict(name="Purple Cabbage Micro", name_hi="माइक्रो पत्तागोभी", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=99, unit="100g", stock_quantity=15, is_available=True,
             description="Tender micro purple cabbage",
             image_url="https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80"),
        dict(name="Dragon Fruit", name_hi="ड्रैगन फ्रूट", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=149, unit="piece", stock_quantity=20, is_available=True, is_featured=True,
             description="Fresh pink dragon fruit",
             image_url="https://images.unsplash.com/photo-1527325678964-54921661f888?w=400&q=80"),
        dict(name="Kiwi", name_hi="कीवी", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=39, unit="piece", stock_quantity=50, is_available=True, is_featured=True,
             description="Fresh green kiwi fruit",
             image_url="https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?w=400&q=80"),
        dict(name="Avocado", name_hi="एवोकाडो", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=99, unit="piece", stock_quantity=25, is_available=True,
             description="Ripe creamy avocado",
             image_url="https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80"),
        dict(name="Passion Fruit", name_hi="पैशन फ्रूट", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=59, unit="piece", stock_quantity=20, is_available=True,
             description="Fresh passion fruit",
             image_url="https://images.unsplash.com/photo-1604495772376-9657f0035eb5?w=400&q=80"),
        dict(name="Blueberries", name_hi="ब्लूबेरी", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=199, unit="125g", stock_quantity=20, is_available=True,
             description="Fresh imported blueberries",
             image_url="https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&q=80"),
        dict(name="Strawberries", name_hi="स्ट्रॉबेरी", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=129, unit="250g", stock_quantity=25, is_available=True, is_featured=True,
             description="Fresh juicy strawberries",
             image_url="https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80"),
        dict(name="Green Grapes (Seedless)", name_hi="हरे अंगूर", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=89, unit="500g", stock_quantity=30, is_available=True,
             description="Sweet seedless green grapes",
             image_url="https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&q=80"),
        dict(name="Raspberries", name_hi="रास्पबेरी", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=219, unit="125g", stock_quantity=15, is_available=True,
             description="Fresh raspberries",
             image_url="https://images.unsplash.com/photo-1495531149620-b7813cd20a83?w=400&q=80"),
    ]
    for item in exotic:
        db.session.add(Product(**item))
    db.session.commit()
    print(f"Seeded {len(exotic)} exotic products.")

def _seed_sample_products():
    """Seed all products. Runs every startup to handle ephemeral filesystems (Render etc)."""    from app.models.product import Product
    count = Product.query.count()
    if count >= 20:
        # Add exotic if missing
        if not Product.query.filter(Product.category.in_(['exotic_vegetable','exotic_fruit'])).first():
            _seed_exotic_only()
        return
    sample = [
        # ── VEGETABLES ────────────────────────────────────────
        dict(name="Fresh Ivy Gourd (Kundru)", name_hi="कुंदरू", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=17, unit="250g", stock_quantity=50, is_available=True,
             description="Fresh tender Kundru, ideal for stir-fry",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Wild Melon (Kachri)", name_hi="काचरी", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=13, unit="250g", stock_quantity=40, is_available=True,
             description="Fresh Kachri, a Rajasthani special",
             image_url="https://images.unsplash.com/photo-1571575173700-afb9492e6a50?w=400&q=80"),
        dict(name="Broccoli", name_hi="ब्रोकोली", category="vegetable", tags="vegetable",
             price_per_unit=38, unit="piece", stock_quantity=30, is_available=True,
             description="Fresh green broccoli, 200-300g per unit",
             image_url="https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400&q=80"),
        dict(name="Fresh Garlic (Lehsun)", name_hi="लहसुन", category="vegetable", tags="vegetable",
             price_per_unit=33, unit="200g", stock_quantity=80, is_available=True,
             description="Fresh garlic cloves, aromatic and pungent",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Fresh Green Chilli", name_hi="हरी मिर्च", category="vegetable", tags="vegetable",
             price_per_unit=13, unit="100g", stock_quantity=100, is_available=True,
             description="Fresh green chillies, 100-110g",
             image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&q=80"),
        dict(name="Desi Tomato", name_hi="देसी टमाटर", category="vegetable", tags="vegetable",
             price_per_unit=17, unit="500g", stock_quantity=150, is_available=True,
             description="Fresh desi tomatoes 510-520g",
             image_url="https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&q=80"),
        dict(name="Fresh Mushroom Packet", name_hi="मशरूम", category="vegetable", tags="vegetable",
             price_per_unit=41, unit="180g", stock_quantity=40, is_available=True,
             description="Fresh button mushrooms, 180-200g pack",
             image_url="https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=400&q=80"),
        dict(name="Red Cabbage", name_hi="लाल पत्तागोभी", category="vegetable", tags="vegetable",
             price_per_unit=44, unit="300g", stock_quantity=30, is_available=True,
             description="Fresh red cabbage, 300-500g",
             image_url="https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80"),
        dict(name="Cauliflower", name_hi="फूलगोभी", category="vegetable", tags="vegetable",
             price_per_unit=28, unit="piece", stock_quantity=60, is_available=True,
             description="Fresh cauliflower 300-500g per unit",
             image_url="https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=400&q=80"),
        dict(name="Spring Onion", name_hi="हरा प्याज़", category="vegetable", tags="vegetable,leafy",
             price_per_unit=14, unit="250g", stock_quantity=60, is_available=True,
             description="Fresh spring onions, great for salads",
             image_url="https://images.unsplash.com/photo-1599909533731-c5b86a990527?w=400&q=80"),
        dict(name="Drumstick (Sahjan)", name_hi="सहजन", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=40, unit="250g", stock_quantity=30, is_available=True,
             description="Fresh drumsticks, rich in nutrients",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Neem Leaves Bunch", name_hi="नीम की पत्तियाँ", category="leafy", tags="leafy,seasonal",
             price_per_unit=12, unit="bunch", stock_quantity=20, is_available=True,
             description="Fresh neem leaves, medicinal and aromatic",
             image_url="https://images.unsplash.com/photo-1518335935020-cfd6580c1ab4?w=400&q=80"),
        dict(name="Betel Leaves", name_hi="पान के पत्ते", category="leafy", tags="leafy",
             price_per_unit=22, unit="5 units", stock_quantity=30, is_available=True,
             description="Fresh betel leaves",
             image_url="https://images.unsplash.com/photo-1518335935020-cfd6580c1ab4?w=400&q=80"),
        dict(name="Bottle Gourd (Lauki)", name_hi="लौकी", category="vegetable", tags="vegetable",
             price_per_unit=28, unit="400g", stock_quantity=50, is_available=True,
             description="Fresh bottle gourd 400-600g",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Cabbage", name_hi="पत्तागोभी", category="vegetable", tags="vegetable",
             price_per_unit=15, unit="piece", stock_quantity=50, is_available=True,
             description="Fresh cabbage 400-600g per unit",
             image_url="https://images.unsplash.com/photo-1550411294-2f90c26c8fe6?w=400&q=80"),
        dict(name="Sambhar Onion", name_hi="सांभर प्याज़", category="vegetable", tags="vegetable",
             price_per_unit=9, unit="250g", stock_quantity=80, is_available=True,
             description="Small sambhar onions",
             image_url="https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&q=80"),
        dict(name="Small Purple Brinjal", name_hi="बैंगन", category="vegetable", tags="vegetable",
             price_per_unit=18, unit="250g", stock_quantity=50, is_available=True,
             description="Small purple brinjal 250-300g",
             image_url="https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=400&q=80"),
        dict(name="Green Lettuce", name_hi="लेट्यूस", category="leafy", tags="leafy",
             price_per_unit=18, unit="100g", stock_quantity=30, is_available=True,
             description="Fresh green lettuce",
             image_url="https://images.unsplash.com/photo-1621955964441-c173e01c135b?w=400&q=80"),
        dict(name="Radish", name_hi="मूली", category="vegetable", tags="vegetable",
             price_per_unit=11, unit="250g", stock_quantity=60, is_available=True,
             description="Fresh white radish 250-300g",
             image_url="https://images.unsplash.com/photo-1585669282669-2ec991a66a09?w=400&q=80"),
        dict(name="Fresh Picador Chilli", name_hi="पिकाडोर मिर्च", category="vegetable", tags="vegetable",
             price_per_unit=16, unit="250g", stock_quantity=40, is_available=True,
             description="Fresh Picador chilli 250-270g",
             image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&q=80"),
        dict(name="Fresh Spinach Bunch", name_hi="पालक", category="leafy", tags="leafy,vegetable",
             price_per_unit=14, unit="200g", stock_quantity=80, is_available=True, is_featured=True,
             description="Fresh green spinach bunch",
             image_url="https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&q=80"),
        dict(name="Baby Bottle Gourd", name_hi="छोटी लौकी", category="vegetable", tags="vegetable",
             price_per_unit=15, unit="piece", stock_quantity=30, is_available=True,
             description="Small baby bottle gourd 250-350g",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Holy Tulsi", name_hi="तुलसी", category="leafy", tags="leafy,seasonal",
             price_per_unit=15, unit="10g", stock_quantity=20, is_available=True,
             description="Fresh holy basil (Tulsi)",
             image_url="https://images.unsplash.com/photo-1518335935020-cfd6580c1ab4?w=400&q=80"),
        dict(name="Fresh Yellow Zucchini", name_hi="तोरी", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=54, unit="piece", stock_quantity=20, is_available=True,
             description="Fresh yellow zucchini 200-250g",
             image_url="https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?w=400&q=80"),
        dict(name="Fresh Baby Corn", name_hi="बेबी कॉर्न", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=44, unit="200g", stock_quantity=30, is_available=True,
             description="Fresh baby corn",
             image_url="https://images.unsplash.com/photo-1601593768799-76e1d8ad9ab7?w=400&q=80"),
        dict(name="Fresh Garland Marigold", name_hi="गेंदा फूल", category="seasonal", tags="seasonal",
             price_per_unit=38, unit="piece", stock_quantity=20, is_available=True,
             description="Fresh orange marigold garland 2-2.5 ft",
             image_url="https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&q=80"),
        dict(name="Sweet Corn (Packet)", name_hi="मकई", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=14, unit="piece", stock_quantity=50, is_available=True,
             description="Sweet corn 180-200g",
             image_url="https://images.unsplash.com/photo-1601593768799-76e1d8ad9ab7?w=400&q=80"),
        dict(name="Fresh Ridge Gourd (Turai)", name_hi="तुरई", category="vegetable", tags="vegetable",
             price_per_unit=55, unit="500g", stock_quantity=40, is_available=True,
             description="Fresh ridge gourd 500-600g",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Fresh Mint Leaves (Pudina)", name_hi="पुदीना", category="leafy", tags="leafy",
             price_per_unit=10, unit="100g", stock_quantity=60, is_available=True, is_featured=True,
             description="Fresh aromatic mint leaves",
             image_url="https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&q=80"),
        dict(name="Bok Choy", name_hi="बोक चॉय", category="leafy", tags="leafy,seasonal",
             price_per_unit=25, unit="200g", stock_quantity=20, is_available=True,
             description="Fresh bok choy 200-250g",
             image_url="https://images.unsplash.com/photo-1621955964441-c173e01c135b?w=400&q=80"),
        dict(name="Local Carrot (Halwa)", name_hi="गाजर", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=35, unit="2kg", stock_quantity=50, is_available=True,
             description="Fresh local carrot, great for halwa",
             image_url="https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80"),
        dict(name="Green Tomato", name_hi="हरा टमाटर", category="vegetable", tags="vegetable",
             price_per_unit=20, unit="500g", stock_quantity=40, is_available=True,
             description="Fresh green tomatoes",
             image_url="https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&q=80"),
        dict(name="Fresh Beetroot (Chukandar)", name_hi="चुकंदर", category="vegetable", tags="vegetable",
             price_per_unit=19, unit="500g", stock_quantity=40, is_available=True,
             description="Fresh beetroot 500-600g",
             image_url="https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=400&q=80"),
        dict(name="Iceberg Lettuce", name_hi="आइसबर्ग लेट्यूस", category="leafy", tags="leafy",
             price_per_unit=51, unit="200g", stock_quantity=20, is_available=True,
             description="Fresh iceberg lettuce",
             image_url="https://images.unsplash.com/photo-1621955964441-c173e01c135b?w=400&q=80"),
        dict(name="Black Brinjal (Bhartaa)", name_hi="भरता बैंगन", category="vegetable", tags="vegetable",
             price_per_unit=26, unit="500g", stock_quantity=40, is_available=True,
             description="Black brinjal for bharta 500-700g",
             image_url="https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=400&q=80"),
        dict(name="Fresh Green Capsicum", name_hi="शिमला मिर्च", category="vegetable", tags="vegetable",
             price_per_unit=16, unit="250g", stock_quantity=50, is_available=True, is_featured=True,
             description="Fresh green capsicum 250-350g",
             image_url="https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80"),
        dict(name="Apple Ber", name_hi="बेर", category="fruit", tags="fruit,seasonal",
             price_per_unit=28, unit="250g", stock_quantity=30, is_available=True,
             description="Fresh apple ber (Indian jujube)",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Unpeeled Green Chana", name_hi="हरा चना", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=22, unit="200g", stock_quantity=30, is_available=True,
             description="Fresh unpeeled green chana",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Rose Flowers & Petals", name_hi="गुलाब", category="seasonal", tags="seasonal",
             price_per_unit=25, unit="100g", stock_quantity=20, is_available=True,
             description="Fresh rose flowers and petals",
             image_url="https://images.unsplash.com/photo-1464582883107-8adf2dca8a9f?w=400&q=80"),
        dict(name="Red Carrot", name_hi="लाल गाजर", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=12, unit="500g", stock_quantity=60, is_available=True,
             description="Fresh red carrot 500-550g",
             image_url="https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&q=80"),
        dict(name="Hybrid Tomato", name_hi="हाइब्रिड टमाटर", category="vegetable", tags="vegetable",
             price_per_unit=15, unit="500g", stock_quantity=100, is_available=True, is_featured=True,
             description="Fresh hybrid tomato 510-520g",
             image_url="https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&q=80"),
        dict(name="English Cucumber", name_hi="खीरा", category="vegetable", tags="vegetable",
             price_per_unit=19, unit="500g", stock_quantity=60, is_available=True,
             description="Fresh English cucumber 500-600g",
             image_url="https://images.unsplash.com/photo-1566486189376-d5f21e25aae4?w=400&q=80"),
        dict(name="Fresh Lady Finger (Bhindi)", name_hi="भिंडी", category="vegetable", tags="vegetable",
             price_per_unit=22, unit="250g", stock_quantity=70, is_available=True, is_featured=True,
             description="Fresh tender lady finger",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Red Chilli", name_hi="लाल मिर्च", category="vegetable", tags="vegetable",
             price_per_unit=13, unit="100g", stock_quantity=50, is_available=True,
             description="Fresh red chillies",
             image_url="https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&q=80"),
        dict(name="Long Brinjal", name_hi="लंबा बैंगन", category="vegetable", tags="vegetable",
             price_per_unit=25, unit="500g", stock_quantity=40, is_available=True,
             description="Long brinjal 500-550g",
             image_url="https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=400&q=80"),
        dict(name="Marigold Petals", name_hi="गेंदे की पंखुड़ी", category="seasonal", tags="seasonal",
             price_per_unit=28, unit="pack of 2", stock_quantity=20, is_available=True,
             description="Fresh marigold petals for pooja",
             image_url="https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&q=80"),
        dict(name="Potato (New Crop)", name_hi="आलू", category="vegetable", tags="vegetable",
             price_per_unit=13, unit="kg", stock_quantity=200, is_available=True, is_featured=True,
             description="Farm fresh new crop potato",
             image_url="https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&q=80"),
        dict(name="Sponge Gourd", name_hi="तोरई", category="vegetable", tags="vegetable",
             price_per_unit=49, unit="500g", stock_quantity=30, is_available=True,
             description="Fresh sponge gourd 500-550g",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Lemongrass", name_hi="लेमनग्रास", category="leafy", tags="leafy,seasonal",
             price_per_unit=20, unit="100g", stock_quantity=20, is_available=True,
             description="Fresh lemongrass",
             image_url="https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&q=80"),
        dict(name="Fresh Basil Leaves", name_hi="तुलसी पत्ता", category="leafy", tags="leafy",
             price_per_unit=20, unit="50g", stock_quantity=20, is_available=True,
             description="Fresh Italian basil leaves",
             image_url="https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400&q=80"),
        dict(name="Fresh Baby Potato", name_hi="बेबी आलू", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=8, unit="500g", stock_quantity=60, is_available=True,
             description="Fresh baby potatoes",
             image_url="https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&q=80"),
        dict(name="Fresh French Beans", name_hi="फ्रेंच बीन्स", category="vegetable", tags="vegetable",
             price_per_unit=22, unit="250g", stock_quantity=40, is_available=True,
             description="Fresh French beans",
             image_url="https://images.unsplash.com/photo-1564590260878-b64b4f3a7e2d?w=400&q=80"),
        dict(name="Coriander Bunch", name_hi="धनिया", category="leafy", tags="leafy",
             price_per_unit=11, unit="100g", stock_quantity=100, is_available=True, is_featured=True,
             description="Fresh coriander bunch",
             image_url="https://images.unsplash.com/photo-1590868309235-ea34bed7bd7f?w=400&q=80"),
        dict(name="American Sweet Corn", name_hi="मकई", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=17, unit="piece", stock_quantity=50, is_available=True,
             description="American sweet corn cob",
             image_url="https://images.unsplash.com/photo-1601593768799-76e1d8ad9ab7?w=400&q=80"),
        dict(name="Fresh Bitter Gourd (Karela)", name_hi="करेला", category="vegetable", tags="vegetable",
             price_per_unit=28, unit="250g", stock_quantity=40, is_available=True,
             description="Fresh bitter gourd 250-300g",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Green Zucchini", name_hi="हरी तोरी", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=25, unit="piece", stock_quantity=20, is_available=True,
             description="Fresh green zucchini 150-200g",
             image_url="https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?w=400&q=80"),
        dict(name="Onion", name_hi="प्याज़", category="vegetable", tags="vegetable",
             price_per_unit=24, unit="kg", stock_quantity=200, is_available=True, is_featured=True,
             description="Fresh onion 1 Kg",
             image_url="https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&q=80"),
        dict(name="Red Potato", name_hi="लाल आलू", category="vegetable", tags="vegetable",
             price_per_unit=30, unit="kg", stock_quantity=100, is_available=True,
             description="Fresh red potato 1 Kg",
             image_url="https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&q=80"),
        dict(name="Groundnut", name_hi="मूंगफली", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=33, unit="250g", stock_quantity=40, is_available=True,
             description="Fresh groundnut",
             image_url="https://images.unsplash.com/photo-1567880905822-56f8e06fe630?w=400&q=80"),
        dict(name="Fresh Red Capsicum", name_hi="लाल शिमला मिर्च", category="vegetable", tags="vegetable",
             price_per_unit=23, unit="125g", stock_quantity=30, is_available=True,
             description="Fresh red capsicum 125-175g",
             image_url="https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80"),
        dict(name="Fresh Colocasia (Arbi)", name_hi="अरबी", category="vegetable", tags="vegetable",
             price_per_unit=12, unit="250g", stock_quantity=40, is_available=True,
             description="Fresh arbi 250-300g",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Rosemary Fresh", name_hi="रोज़मेरी", category="leafy", tags="leafy,seasonal",
             price_per_unit=13, unit="10g", stock_quantity=15, is_available=True,
             description="Fresh rosemary herb",
             image_url="https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400&q=80"),
        dict(name="Fresh Ginger (Adrak)", name_hi="अदरक", category="vegetable", tags="vegetable",
             price_per_unit=15, unit="200g", stock_quantity=80, is_available=True, is_featured=True,
             description="Fresh ginger 200g",
             image_url="https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&q=80"),
        dict(name="Puja Flowers Mix", name_hi="पूजा फूल", category="seasonal", tags="seasonal",
             price_per_unit=26, unit="100g", stock_quantity=30, is_available=True,
             description="Mixed fresh flowers for puja 100g",
             image_url="https://images.unsplash.com/photo-1444930694458-01babf71870c?w=400&q=80"),
        # ── FRUITS ────────────────────────────────────────────
        dict(name="Fresh Lime (Mosambi)", name_hi="मौसंबी", category="fruit", tags="fruit,seasonal",
             price_per_unit=28, unit="500g", stock_quantity=60, is_available=True,
             description="Fresh sweet lime 500-700g",
             image_url="https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=400&q=80"),
        dict(name="Raw Papaya", name_hi="कच्चा पपीता", category="fruit", tags="fruit,seasonal",
             price_per_unit=28, unit="400g", stock_quantity=30, is_available=True,
             description="Fresh raw papaya 400-600g",
             image_url="https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=400&q=80"),
        dict(name="Pomegranate (3 Pieces)", name_hi="अनार", category="fruit", tags="fruit,seasonal",
             price_per_unit=150, unit="3 pieces", stock_quantity=40, is_available=True,
             description="Fresh pomegranate 500-700g each",
             image_url="https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&q=80"),
        dict(name="Red Cherry", name_hi="चेरी", category="fruit", tags="fruit,seasonal",
             price_per_unit=184, unit="100g", stock_quantity=20, is_available=True,
             description="Fresh imported red cherries",
             image_url="https://images.unsplash.com/photo-1528821128474-27f963b062bf?w=400&q=80"),
        dict(name="Pomegranate Regular", name_hi="अनार", category="fruit", tags="fruit",
             price_per_unit=180, unit="kg", stock_quantity=40, is_available=True,
             description="Fresh regular pomegranate, 1 Kg",
             image_url="https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&q=80"),
        dict(name="Plum (Imported)", name_hi="आलूबुखारा", category="fruit", tags="fruit,seasonal",
             price_per_unit=60, unit="200g", stock_quantity=25, is_available=True,
             description="Fresh imported plums",
             image_url="https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400&q=80"),
        dict(name="Sweet Tamarind (Imli)", name_hi="इमली", category="fruit", tags="fruit,seasonal",
             price_per_unit=102, unit="box", stock_quantity=20, is_available=True,
             description="Fresh sweet tamarind box, 225g",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Packham Pear (Imported)", name_hi="नाशपाती", category="fruit", tags="fruit,seasonal",
             price_per_unit=80, unit="2 pieces", stock_quantity=25, is_available=True,
             description="Imported Packham pear 300-350g each",
             image_url="https://images.unsplash.com/photo-1571575173700-afb9492e6a50?w=400&q=80"),
        dict(name="Black Grapes", name_hi="काले अंगूर", category="fruit", tags="fruit,seasonal",
             price_per_unit=66, unit="200g", stock_quantity=30, is_available=True,
             description="Fresh black grapes 200-250g",
             image_url="https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&q=80"),
        dict(name="Fresh Pineapple", name_hi="अनानास", category="fruit", tags="fruit,seasonal",
             price_per_unit=80, unit="piece", stock_quantity=20, is_available=True,
             description="Fresh pineapple 1-1.4 Kg",
             image_url="https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?w=400&q=80"),
        dict(name="Blueberry (Imported)", name_hi="ब्लूबेरी", category="fruit", tags="fruit,seasonal",
             price_per_unit=196, unit="125g", stock_quantity=20, is_available=True,
             description="Fresh imported blueberries",
             image_url="https://images.unsplash.com/photo-1457296898342-cdd24585d095?w=400&q=80"),
        dict(name="Raw Mango", name_hi="कच्चा आम", category="fruit", tags="fruit,seasonal",
             price_per_unit=29, unit="200g", stock_quantity=40, is_available=True,
             description="Raw green mango 200-300g",
             image_url="https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80"),
        dict(name="Red Delicious Apple", name_hi="लाल सेब", category="fruit", tags="fruit",
             price_per_unit=112, unit="2 pieces", stock_quantity=35, is_available=True,
             description="Red delicious apple 225-325g each",
             image_url="https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80"),
        dict(name="Safeda Mango", name_hi="सफेदा आम", category="fruit", tags="fruit,seasonal",
             price_per_unit=138, unit="2 pieces", stock_quantity=30, is_available=True, is_featured=True,
             description="Sweet Safeda mango 550-700g each",
             image_url="https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80"),
        dict(name="Dragon Fruit (Imported)", name_hi="ड्रैगन फ्रूट", category="fruit", tags="fruit,seasonal",
             price_per_unit=95, unit="piece", stock_quantity=15, is_available=True,
             description="Imported dragon fruit 300-400g",
             image_url="https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400&q=80"),
        dict(name="Longan (Imported)", name_hi="लोंगन", category="fruit", tags="fruit,seasonal",
             price_per_unit=78, unit="200g", stock_quantity=15, is_available=True,
             description="Fresh imported longan 200g",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Grapefruit (Chakota)", name_hi="चकोतरा", category="fruit", tags="fruit,seasonal",
             price_per_unit=78, unit="piece", stock_quantity=15, is_available=True,
             description="Imported grapefruit 200-240g",
             image_url="https://images.unsplash.com/photo-1587888637140-849b3f8a24b8?w=400&q=80"),
        dict(name="Shimla Apple (4 Pieces)", name_hi="शिमला सेब", category="fruit", tags="fruit",
             price_per_unit=102, unit="pack", stock_quantity=30, is_available=True,
             description="Shimla apple 4 pieces 500-550g",
             image_url="https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80"),
        dict(name="Totapuri Mango", name_hi="तोतापुरी आम", category="fruit", tags="fruit,seasonal",
             price_per_unit=110, unit="2 pieces", stock_quantity=25, is_available=True, is_featured=True,
             description="Totapuri mango 500-600g each",
             image_url="https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80"),
        dict(name="Kashmir Delicious Apple", name_hi="कश्मीरी सेब", category="fruit", tags="fruit",
             price_per_unit=130, unit="4 pieces", stock_quantity=30, is_available=True, is_featured=True,
             description="Kashmir delicious apple 500-600g each",
             image_url="https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80"),
        dict(name="Tender Coconut", name_hi="नारियल", category="fruit", tags="fruit,seasonal",
             price_per_unit=54, unit="piece", stock_quantity=30, is_available=True,
             description="Fresh tender coconut for drinking",
             image_url="https://images.unsplash.com/photo-1511689774938-ddb2f78c1f41?w=400&q=80"),
        dict(name="Sapota (Chikoo)", name_hi="चीकू", category="fruit", tags="fruit,seasonal",
             price_per_unit=38, unit="400g", stock_quantity=30, is_available=True,
             description="Fresh chikoo 400-500g",
             image_url="https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80"),
        dict(name="Shimla Apple (Small)", name_hi="शिमला सेब", category="fruit", tags="fruit",
             price_per_unit=118, unit="500g", stock_quantity=40, is_available=True, is_featured=True,
             description="Small Shimla apple 500g pack",
             image_url="https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80"),
        dict(name="Navel Orange (Imported)", name_hi="संतरा", category="fruit", tags="fruit,seasonal",
             price_per_unit=74, unit="piece", stock_quantity=30, is_available=True,
             description="Imported navel orange 350-450g",
             image_url="https://images.unsplash.com/photo-1547514701-42782101795e?w=400&q=80"),
        dict(name="Red Globe Grapes", name_hi="लाल अंगूर", category="fruit", tags="fruit,seasonal",
             price_per_unit=80, unit="200g", stock_quantity=25, is_available=True,
             description="Fresh red globe grapes 200-250g",
             image_url="https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&q=80"),
        dict(name="Grapes Sonaka", name_hi="सोनाका अंगूर", category="fruit", tags="fruit,seasonal",
             price_per_unit=52, unit="250g", stock_quantity=30, is_available=True,
             description="Fresh Sonaka grapes",
             image_url="https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&q=80"),
        dict(name="New Zealand Royal Gala Apple", name_hi="गाला सेब", category="fruit", tags="fruit",
             price_per_unit=115, unit="2 pieces", stock_quantity=20, is_available=True,
             description="NZ Royal Gala apple 300-400g each",
             image_url="https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80"),
        dict(name="Muskmelon", name_hi="खरबूजा", category="fruit", tags="fruit,seasonal",
             price_per_unit=26, unit="piece", stock_quantity=25, is_available=True,
             description="Fresh muskmelon 400-700g",
             image_url="https://images.unsplash.com/photo-1571575173700-afb9492e6a50?w=400&q=80"),
        dict(name="Kashmiri Apple (2 pieces)", name_hi="कश्मीरी सेब", category="fruit", tags="fruit",
             price_per_unit=68, unit="2 pieces", stock_quantity=35, is_available=True,
             description="Kashmiri apple 280-350g each",
             image_url="https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80"),
        dict(name="Kinnow", name_hi="किन्नू", category="fruit", tags="fruit,seasonal",
             price_per_unit=32, unit="500g", stock_quantity=40, is_available=True,
             description="Fresh kinnow 500g",
             image_url="https://images.unsplash.com/photo-1547514701-42782101795e?w=400&q=80"),
        dict(name="Fresh Kiwi", name_hi="कीवी", category="fruit", tags="fruit,seasonal",
             price_per_unit=65, unit="3 units", stock_quantity=25, is_available=True,
             description="Fresh kiwi 3 units",
             image_url="https://images.unsplash.com/photo-1585059895524-72359e06133a?w=400&q=80"),
        dict(name="Fresh Kiran Watermelon", name_hi="तरबूज", category="fruit", tags="fruit,seasonal",
             price_per_unit=95, unit="piece", stock_quantity=20, is_available=True, is_featured=True,
             description="Fresh Kiran watermelon 2-3 Kg",
             image_url="https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&q=80"),
        dict(name="Avocado (Imported)", name_hi="एवोकैडो", category="fruit", tags="fruit,seasonal",
             price_per_unit=95, unit="piece", stock_quantity=15, is_available=True,
             description="Imported avocado 150-200g",
             image_url="https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=400&q=80"),
        dict(name="Lemon", name_hi="नींबू", category="fruit", tags="fruit",
             price_per_unit=29, unit="200g", stock_quantity=100, is_available=True, is_featured=True,
             description="Fresh lemons 200g",
             image_url="https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=400&q=80"),
        dict(name="Baby Banana (Robusta)", name_hi="छोटा केला", category="fruit", tags="fruit",
             price_per_unit=25, unit="4 units", stock_quantity=50, is_available=True,
             description="Fresh baby banana Robusta variety",
             image_url="https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=400&q=80"),
        dict(name="Fresh Yellow Capsicum", name_hi="पीली शिमला मिर्च", category="vegetable", tags="vegetable",
             price_per_unit=23, unit="125g", stock_quantity=30, is_available=True,
             description="Fresh yellow capsicum 125-175g",
             image_url="https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80"),
        dict(name="Zespri Green Kiwi", name_hi="कीवी", category="fruit", tags="fruit,seasonal",
             price_per_unit=89, unit="2 pieces", stock_quantity=20, is_available=True,
             description="Zespri green kiwi",
             image_url="https://images.unsplash.com/photo-1585059895524-72359e06133a?w=400&q=80"),
        dict(name="Fresh Thai Guava", name_hi="अमरूद", category="fruit", tags="fruit,seasonal",
             price_per_unit=65, unit="500g", stock_quantity=25, is_available=True,
             description="Fresh Thai guava 500-700g",
             image_url="https://images.unsplash.com/photo-1536511132770-e5058c7e8c46?w=400&q=80"),
        dict(name="Raw Banana (Plantains)", name_hi="कच्चा केला", category="fruit", tags="fruit,seasonal",
             price_per_unit=21, unit="3 pieces", stock_quantity=40, is_available=True,
             description="Fresh raw banana plantains",
             image_url="https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=400&q=80"),
        dict(name="Brown Coconut", name_hi="नारियल", category="fruit", tags="fruit",
             price_per_unit=34, unit="piece", stock_quantity=40, is_available=True,
             description="Fresh brown coconut",
             image_url="https://images.unsplash.com/photo-1511689774938-ddb2f78c1f41?w=400&q=80"),
        dict(name="Fresh Papaya", name_hi="पपीता", category="fruit", tags="fruit,seasonal",
             price_per_unit=48, unit="piece", stock_quantity=30, is_available=True,
             description="Fresh papaya 700g-1 Kg",
             image_url="https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=400&q=80"),
        dict(name="Mini Orange", name_hi="नारंगी", category="fruit", tags="fruit,seasonal",
             price_per_unit=65, unit="200g", stock_quantity=30, is_available=True,
             description="Fresh mini orange",
             image_url="https://images.unsplash.com/photo-1547514701-42782101795e?w=400&q=80"),
        dict(name="Green Peas", name_hi="मटर", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=18, unit="250g", stock_quantity=80, is_available=True, is_featured=True,
             description="Fresh green peas 250-270g",
             image_url="https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=400&q=80"),
        dict(name="Curry Leaves", name_hi="करी पत्ता", category="leafy", tags="leafy",
             price_per_unit=15, unit="50g", stock_quantity=50, is_available=True,
             description="Fresh aromatic curry leaves",
             image_url="https://images.unsplash.com/photo-1518335935020-cfd6580c1ab4?w=400&q=80"),
        dict(name="Green Pumpkin (Kaddu)", name_hi="हरा कद्दू", category="vegetable", tags="vegetable",
             price_per_unit=39, unit="piece", stock_quantity=30, is_available=True,
             description="Fresh green pumpkin 1-1.5 Kg",
             image_url="https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=400&q=80"),
        dict(name="Raw Turmeric", name_hi="कच्ची हल्दी", category="vegetable", tags="vegetable,seasonal",
             price_per_unit=11, unit="250g", stock_quantity=30, is_available=True,
             description="Raw turmeric 250-270g",
             image_url="https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&q=80"),

        # ── EXOTIC VEGETABLES ─────────────────────────────────
        dict(name="Asparagus", name_hi="शतावरी", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=129, unit="200g", stock_quantity=20, is_available=True, is_featured=True,
             description="Fresh green asparagus spears, great for grilling or stir fry",
             image_url="https://images.unsplash.com/photo-1539375665275-f9de415ef9ac?w=400&q=80"),
        dict(name="Cherry Tomatoes", name_hi="चेरी टमाटर", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=89, unit="250g", stock_quantity=30, is_available=True,
             description="Sweet and tangy cherry tomatoes, perfect for salads",
             image_url="https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400&q=80"),
        dict(name="Red Bell Pepper", name_hi="लाल शिमला मिर्च", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=79, unit="piece", stock_quantity=40, is_available=True,
             description="Sweet red capsicum, vibrant colour and mild flavour",
             image_url="https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80"),
        dict(name="Yellow Bell Pepper", name_hi="पीली शिमला मिर्च", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=79, unit="piece", stock_quantity=40, is_available=True,
             description="Sweet yellow capsicum, mild and crunchy",
             image_url="https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&q=80"),
        dict(name="Zucchini (Green)", name_hi="हरी तोरी", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=69, unit="piece", stock_quantity=25, is_available=True,
             description="Fresh green zucchini 200-250g, ideal for pasta and grills",
             image_url="https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?w=400&q=80"),
        dict(name="Portobello Mushroom", name_hi="पोर्टोबेलो मशरूम", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=149, unit="200g", stock_quantity=15, is_available=True,
             description="Large meaty portobello mushrooms, great for burgers and grills",
             image_url="https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=400&q=80"),
        dict(name="Celery", name_hi="अजमोद", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=59, unit="200g", stock_quantity=20, is_available=True,
             description="Fresh crispy celery stalks, great for juices and salads",
             image_url="https://images.unsplash.com/photo-1556801712-76c8eb07bbc9?w=400&q=80"),
        dict(name="Purple Cabbage Micro", name_hi="माइक्रो पत्तागोभी", category="exotic_vegetable", tags="exotic_vegetable,exotic",
             price_per_unit=99, unit="100g", stock_quantity=15, is_available=True,
             description="Tender micro purple cabbage, packed with antioxidants",
             image_url="https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80"),

        # ── EXOTIC FRUITS ─────────────────────────────────────
        dict(name="Dragon Fruit", name_hi="ड्रैगन फ्रूट", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=149, unit="piece", stock_quantity=20, is_available=True, is_featured=True,
             description="Fresh pink dragon fruit, sweet and rich in antioxidants",
             image_url="https://images.unsplash.com/photo-1527325678964-54921661f888?w=400&q=80"),
        dict(name="Kiwi", name_hi="कीवी", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=39, unit="piece", stock_quantity=50, is_available=True, is_featured=True,
             description="Fresh green kiwi fruit, tangy and vitamin C rich",
             image_url="https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?w=400&q=80"),
        dict(name="Avocado", name_hi="एवोकाडो", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=99, unit="piece", stock_quantity=25, is_available=True,
             description="Ripe creamy avocado, perfect for toast and guacamole",
             image_url="https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&q=80"),
        dict(name="Passion Fruit", name_hi="पैशन फ्रूट", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=59, unit="piece", stock_quantity=20, is_available=True,
             description="Fresh passion fruit with aromatic pulp, tangy and sweet",
             image_url="https://images.unsplash.com/photo-1604495772376-9657f0035eb5?w=400&q=80"),
        dict(name="Blueberries", name_hi="ब्लूबेरी", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=199, unit="125g", stock_quantity=20, is_available=True,
             description="Fresh imported blueberries, rich in antioxidants",
             image_url="https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&q=80"),
        dict(name="Strawberries", name_hi="स्ट्रॉबेरी", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=129, unit="250g", stock_quantity=25, is_available=True, is_featured=True,
             description="Fresh juicy strawberries, sweet and bright red",
             image_url="https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&q=80"),
        dict(name="Green Grapes (Seedless)", name_hi="हरे अंगूर", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=89, unit="500g", stock_quantity=30, is_available=True,
             description="Sweet seedless green grapes, fresh and juicy",
             image_url="https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&q=80"),
        dict(name="Raspberries", name_hi="रास्पबेरी", category="exotic_fruit", tags="exotic_fruit,exotic,fruit",
             price_per_unit=219, unit="125g", stock_quantity=15, is_available=True,
             description="Fresh raspberries, delicate and flavourful",
             image_url="https://images.unsplash.com/photo-1495531149620-b7813cd20a83?w=400&q=80"),
    ]
    for item in sample:
        db.session.add(Product(**item))
    db.session.commit()
    print(f"Seeded {len(sample)} products successfully.")